#!/bin/sh
set -e

version=$1
baseVersion=${version%%-*}

if [ ! -f "/boot/loader/entries/${version}.conf" ] ; then

  cat > "/boot/loader/entries/${version}.conf" << EOF
title Gentoo Linux ${baseVersion}
linux /vmlinuz-${version}
initrd /initramfs-${version}.img
options quiet splash

EOF

fi

